services:
  - type: web
    name: memorialcareplaywright
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: web
        source: /
        destination: https://memorialcareplaywright.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: main
    region: oregon
